### ISSUE TITLE
DependsOn with dynamic value ?

### ISSUE THREAD

**Issue by lemattou** [outl1ne/nova-multiselect-field#127]
Hey!

I wanna do someting like that :

`
Multiselect::make('City', 'city')
->placeholder('Sélectionnez')
->saveAsJSON()
->dependsOn('country')
->dependsOnOptions(function($value){
return City::query()->where('country_id',$value)->get()->pluck('name','id')->toArray();
}),
`

Any suggestions, idea ?
Thanks a lot

**Comment by acuatoria** [comment]
I'm looking for this too
