### ISSUE TITLE
work with pivot field (sync)

### ISSUE THREAD

**Issue by anubhav217** [outl1ne/nova-multiselect-field#133]
When using it as a pivot field in a BelongsToMany relation, how to store the values with a pivot attribute ?

example :

public function mainSpecialty()
{
        return $this->belongsToMany(Specialty::class)->wherePivot('is_main', 1);
}

Multiselect::make('Main specialty', 'mainSpecialty')
     ->belongsToMany(\App\Nova\Specialty::class)
The field is retrieve correctly from the database but when it saved, I can't find a way to add the "is_main" pivot attribute.

The fillUsing method seems to do a $relation->sync($request->get($attribute) ?? []); but in this case, the $attribute should be an array like [1 => ['is_main' => 1]] as in the documentation.

Thanks for all !

**Comment by Tarpsvo** [comment]
Hi! Currently, this is not possible without overwriting the ->fillUsing() method.
