### ISSUE TITLE
Nova 4.1 added a dark mode toggle - this package only uses system setting

### ISSUE THREAD

**Issue by dmason30** [outl1ne/nova-multiselect-field#147]
Nova: 4.1
Package: 3.0.1
Laravel: 9.7

<img width="133" alt="image" src="https://user-images.githubusercontent.com/20278756/163023853-021481bb-37b1-4957-a500-f973afc50b91.png">

We end up with the multiselect showing the incorrect them if someone selects either 'Light' or 'Dark' and their system setting is set to the opposite.

Scenario 1:
System setting: Dark
Nova setting: Light
<img width="363" alt="image" src="https://user-images.githubusercontent.com/20278756/163024299-161a90a4-a4df-43cc-a88e-49afc7182b68.png">

Scenario 2:
System setting: Light
Nova setting: Dark
<img width="370" alt="image" src="https://user-images.githubusercontent.com/20278756/163024522-99b49562-ee9e-41fd-b2cd-5a4a1324dac0.png">

**Comment by Tarpsvo** [comment]
Heya! Thanks for the report. It's now been fixed in major release 4.0. The release 4.0 also brings with us a namespace change from OptimistDigital to Outl1ne. Please follow the upgrade directions here: https://github.com/outl1ne/nova-multiselect-field/releases/tag/4.0.0

Thanks!
