### ISSUE TITLE
No Json saved, table asked

### ISSUE THREAD

**Issue by pit07** [outl1ne/nova-multiselect-field#152]
Hi!

Maybe I misconfigured this. I explain:

When creating a coupon, the administrator can link this coupon to a product, or to a product category. So I use this Multiselect.

My discount.php **nova file** :

```
Multiselect::make('Categories', 'categories')
                    ->belongsToMany(\App\Nova\Category::class)
                    ->nullable(true)
                    ->saveAsJSON()
                    ->hideFromIndex()  ,

Multiselect::make('Produits', 'products')
                    ->belongsToMany(\App\Nova\Product::class)
                    ->nullable(true)
                    ->saveAsJSON()
                    ->hideFromIndex() 
```

My discount.php **model file**:

```
public function categories()
{
    return $this->belongsToMany(Category::class);
}

public function products()
{
    return $this->belongsToMany(Product::class);
}
```

In the **discounts table**, i have theses fields:

```
categories (text, nullable)
products (text, nullable)
```

But even by setting the saveAsJson to true, Nova asks me to create a table 

```
category_discount
discount_product
```

And even with that, the linked products are indeed stored in the discount_product table, but the multiselect doesn't display them once the coupon is saved.

And nothing is saved for the categories.

What am I doing wrong?
Thanks a lot!

**Comment by Tarpsvo** [comment]
Hi! BelongsToMany relationships require a pivot table. You should replace the `->belongsToMany(\App\Nova\Product::class)` with `->asyncResource(\App\Nova\Product::class)`.

**Comment by pit07** [comment]
Hi @Tarpsvo !

Thank you for your answer.
It's better!

There is one last concern:

When i update / create:
![image](https://user-images.githubusercontent.com/19688070/174987662-80b9595c-43ab-43b2-b5f2-895e8c9b96f4.png)

... everything is ok in my table.
![image](https://user-images.githubusercontent.com/19688070/174987600-f10708a2-6cfe-4ec5-9520-008f8caabd2b.png)

But on the updated page, fields are not pre-filled.
![image](https://user-images.githubusercontent.com/19688070/174987692-e7e83b42-16d8-4ded-aa3b-e9a91ba5dcd9.png)

Any ideas?
Thanks! <3
Vincent
