### ISSUE TITLE
Data in editing or Details when using HasMany relationship

### ISSUE THREAD

**Issue by francysreymer** [outl1ne/nova-multiselect-field#154]
The data doesnt appear on the form or in details when I am using HasMany relationship.
Can I set something to see the data properly?

**Comment by Tarpsvo** [comment]
Hey! How are you defining your relationship and field?

**Comment by francysreymer** [comment]
` Multiselect::make(__('Tipos de UG'), 'tipoUnidades')
                ->options(TipoUnidade::asArray())
                ->placeholder('Deixe em branco para selecionar todos os tipos de UG')
                ->onlyOnForms(),`

and My Model has the following relationship:
` public function tipoUnidades()
    {
        return $this->hasMany(TipoLayoutTipoUnidade::class);
    }`

**Comment by Tarpsvo** [comment]
You'd have to overwrite the resolve function to give the field a value it understands. Ie `->resolveUsing(fn() => $this->tipoUnidades->pluck('id')->toArray());`
