### ISSUE TITLE
How to customize query for sorting models

### ISSUE THREAD

**Issue by antonwebnauts** [outl1ne/nova-multiselect-field#156]
I use plugin with belongsToMany and I want to get models ordering by createdAt
`
 Multiselect::make('Tags', 'latestTags')
                ->belongsToMany(\App\Nova\Tag::class, true)
`
I made such query in my model, but it gives me no effect
`public function latestTags()
    {
        return $this->tags()->orderBy('id', 'DESC');
    }`
    
How to implement sorting?

**Comment by Tarpsvo** [comment]
You have to create your own endpoint and use the ->api() function.

![image](https://user-images.githubusercontent.com/2018660/169245418-6418e19b-30f0-4051-b780-3f4727c20ece.png)

**Comment by Navi2016** [comment]
Just a tip, what you also could do is use dependsOn to fetch the options from the database, like this:

`Multiselect::make('Market', 'market')
                ->indexCharDisplayLimit(100)
                ->required()
                ->belongsToMany(Market::class, false)
                ->placeholder(' ')
                // depend on a non-existing field, we simply need to load the items with an orderBy, regular ->options does not work
                ->dependsOn('non-existing-field', function (Multiselect $field, NovaRequest $request, FormData $formData) {
                    $options = \App\Models\Market::withoutTrashed()->orderBy('title')->pluck('title', 'id');

                    $field->options($options);
                }),`


using ->options doesnt seem to work, so just use dependsOn with a fake field. Works fine!
