### ISSUE TITLE
computedOptions is empty and undeclared

### ISSUE THREAD

**Issue by jothamhernandez** [outl1ne/nova-multiselect-field#157]
When Using OptionsDependOn without apiUrl, it doesn't work based on expected output

![image](https://user-images.githubusercontent.com/5656719/172370445-d29b2ffe-1cd8-4be3-9f17-0174fd6a9f83.png)

**Comment by Tarpsvo** [comment]
Can you elaborate please?

**Comment by jothamhernandez** [comment]
Based on the README.md, you can used the dependency feature using dependsOn() method, but upon trying it, an error appeared that the method is not defined. I checked the methods available for the Object, and noticed that it should be optionsDependsOn()

I check the source code of the Vue Component, and noticed that the options loads asyncOptions when there is apiUrl provided.

For my case, I haven't provided an apiUrl, but upon checking the code, there is only one instance of that variable on the source code.

To make it short, I'm not able to use the depend on feature.

**Comment by Tarpsvo** [comment]
Seems like I forgot to update the docs. The correct way to define the fields is:

```
Multiselect::make('Country', 'country')
    ->options([
        'IT' => 'Italy',
        'SG' => 'Singapore',
    ]),

Multiselect::make('Language', 'language')
    ->optionsDependOn('country', [
        'IT' => [
            'it' => 'Italian',
        ],
        'SG' => [
            'en' => 'English',
            'ms' => 'Malay',
            'zh' => 'Chinese',
        ]
    ])
    ->optionsDependOnMax([
        'IT' => 1,
        'SG' => 3,
    ]),
```

I just tested it now and it worked.

**Comment by Tarpsvo** [comment]
It can only depend on another Multiselect sadly.
