### ISSUE TITLE
Relation and prefilled options

### ISSUE THREAD

**Issue by ekandreas** [outl1ne/nova-multiselect-field#158]
When using relation belongstomany the options is searchable only. How to prefill options so that the users don't have to search for the result?

**Comment by ekandreas** [comment]
The "false" argument is used but when you are using the api function this doesn't work.

**Comment by Tarpsvo** [comment]
Why are you using api then? Just use ->options()

**Comment by ekandreas** [comment]
Cause options will not be used in this case of relation lookup. And I need to limit the result in the relation, not take them all.

**Comment by Tarpsvo** [comment]
You have access to the resource and model when creating the fields(), wouldn't it be possible to limit the options there?

Ie:
`Multiselect::make()->options(SomeModel::where('type', $this->resource->type)->get()->pluck('name', 'id'))`

**Comment by ekandreas** [comment]
The piped function "options" is not used with the combination of belongstomany

**Comment by ekandreas** [comment]
We found a solution!
Hade to add the related query on the resource to get it right with async=false.
Eg, 
```
    public static function relatableUnits(NovaRequest $request, $query)
    {
        $companyId = $request->user()->company_id;
        return $query->where('company_id', $companyId);
    }
````

**Comment by Tarpsvo** [comment]
Glad to hear it! :)

**Comment by DuyenNguyen66** [comment]
> 

have you used relatableQuery with belongsToMany in MultiSelect? please help me a solution, I'm having a same issue
