### ISSUE TITLE
BelongsToMany Defaults

### ISSUE THREAD

**Issue by ashler2** [outl1ne/nova-multiselect-field#159]
Sorry in advance as this isn't a issue, and more advice on the current limitiations of the project.

I've been looking into using this for a project on nova, but i'm just wondering if its possible to do somthing. With the multiselect using a belongsToMany relationship is it possible to set defaults?

**Comment by kenneth-hendricks** [comment]
I couldn't find a way to do this easily.

As seen here: https://github.com/outl1ne/nova-multiselect-field/blob/main/src/Traits/MultiselectBelongsToSupport.php#L130 When saving the value will use the request value + default to an empty array.

As a work around i added a static listener for a the model i wanted that will set this request attribute if null upon create and it seems to work.

`static::created(function ($model) {
    // Working around inability to provide a default value for nova multiselect 
    Nova::whenServing(function ($request) {
    if (is_null($request->get('target_field'))) {
        $request->merge([
            'programs' => [DEFAULT_VALUE],
        ]);
    }
});`

**Comment by Navi2016** [comment]
Looking for this as well!

**Comment by Navi2016** [comment]
I am willing to pay up to € 300 for someone to implement this, contact me if interested!

**Comment by Tarpsvo** [comment]
Heya. The defaults feature was now released in version 4.3.0.

BelongsToMany, ->api() and ->asyncResource() now all support defaults() in the form of a: single model, array of models or a collection of models. Please test it out and let me know how it fares. Good luck!
