### ISSUE TITLE
No pre-filled fields after creating or updating item.

### ISSUE THREAD

**Issue by pit07** [outl1ne/nova-multiselect-field#165]
Hi everyone!

When i update / create:
![image](https://user-images.githubusercontent.com/19688070/174987662-80b9595c-43ab-43b2-b5f2-895e8c9b96f4.png)

... everything is ok in my table.
![image](https://user-images.githubusercontent.com/19688070/174987600-f10708a2-6cfe-4ec5-9520-008f8caabd2b.png)

But on the updated page, fields are not pre-filled.
![image](https://user-images.githubusercontent.com/19688070/174987692-e7e83b42-16d8-4ded-aa3b-e9a91ba5dcd9.png)

Any ideas?
Thanks! <3

```
Multiselect::make('Categories', 'categories')
                ->asyncResource(\App\Nova\Category::class)
                ->nullable(true)
                ->saveAsJSON(true)
                 ->hideFromIndex()  ,

            Multiselect::make('Produits', 'products')
                ->asyncResource(\App\Nova\Product::class)
                ->nullable(true)
                ->saveAsJSON(true)
                ->hideFromIndex() ,

```

Vincent

**Comment by pit07** [comment]
Nobody ?

**Comment by Tarpsvo** [comment]
I'm unable to reproduce this issue. I think you have to debug it on your side or create a reproducible example for me. :(
