### ISSUE TITLE
Clear button overlaps on long multiselect items

### ISSUE THREAD

**Issue by nxsmtech** [outl1ne/nova-multiselect-field#166]
Nova 3.
This error can be reproduced by adding long value item to multiselect and decreasing screen width. 
Field clear button overlaps clear-item button. 
![image (4)](https://user-images.githubusercontent.com/47241161/178724008-78a101b2-56fa-4029-9e54-de1ede443027.png)
Optionally, there could be added a variable to toggle on/off

**Comment by Tarpsvo** [comment]
Thanks for reporting this! Fixed in version 4.0.6 (Nova 4) and 2.4.1 (Nova 3).
