### ISSUE TITLE
Is anybody here?

### ISSUE THREAD

**Issue by majweb** [outl1ne/nova-multiselect-field#170]
The author is silent the package dies.

**Comment by mstaack** [comment]
Updates come regularly. Packages work really well for me. Don't know what you are talking about.

**Comment by majweb** [comment]
people ask for the option to add a button, select all, for example, a few problems even not touched, so I wonder if there are any updates

**Comment by mstaack** [comment]
Just contribute your specific needs. Welcome to open source 😜

**Comment by Tarpsvo** [comment]
Wow.
