### ISSUE TITLE
Nova 4 `dependsOn` not available

### ISSUE THREAD

**Issue by phlisg** [outl1ne/nova-multiselect-field#174]
Hello,

Comparing Nova 4's native `Multiselect` field and yours, I much prefer the UX & UI your package provides (among other niceties the native field doesn't provide).

Unfortunately, I'm using `Multiselect` as a way to assign `many-to-many` relations in forms screens (create, update), and require the use of `->dependsOn()` ([https://nova.laravel.com/docs/4.0/resources/fields.html#dependent-fields](https://nova.laravel.com/docs/4.0/resources/fields.html#dependent-fields)). 

Extending the `Multiselect` class and adding the `SupportsDependentFields` trait doesn't work:
```php
class Multiselect extends \Outl1ne\MultiselectField\Multiselect
{
    use SupportsDependentFields;
}
```

Thank you for your help

**Comment by phlisg** [comment]
Awesome, thank you! I updated the package and gave it a try, but not sure what I'm trying to do works (toggling readonly attribute).

Actually the `Multiselect` field from Nova itself doesn't work, but a `Select` field does. Maybe a bug there? 

Here's my setup:
```php
Boolean::make('Sync Tags?', 'sync_tags')
    ->hideWhenCreating()
    // some objects are synced from external data streams. If an object was marked "unsynced", the "tags" attribute is therefore writeable
    ->showOnUpdating(fn() => $this->model()->isWriteable('tags'))
    ->fillUsing(fn() => null),

Multiselect::make('Tags', 'tags')
    ->dependsOn(['sync_tags'], fn(Field $field, NovaRequest $request, FormData $formData) => $formData->sync_tags ? $field->readonly(false) : $field->readonly(true))
    // some objects are synced from external data streams. If an object was marked "unsynced", the "tags" attribute is therefore writeable
    ->readonly(fn() => $this->model()->isWriteable('tags'))
    ->options(["some_options"])
    ->flatten()
    ->toArray())

```

I also tried switching the `readonly()` to `show()` and `hide()`, which works.
With a `Select` Field it works using `readonly()`:

```php
Boolean::make('Rompre?', 'sync_categories')
    ->hideWhenCreating()
    ->showOnUpdating(fn() => $this->model()->isWriteable('categories'))
    ->fillUsing(fn() => null),

Select::make('Catégorie principale', 'main_category')
    ->options(Category::all()->mapWithKeys(fn($category) => [$category->id => $category->name]))
    ->dependsOn(['sync_categories'], Is::readable('sync_categories'))
    ->readonly(fn() => $this->model()->isWriteable('categories')),
```

Again, thank you for the quick fix and sorry to come back with my issue. It would be interesting to see whether it's a Nova bug instead.

**Comment by Tarpsvo** [comment]
Heya, sorry about the delay! Version 4.2.0 fixes this issue. :)
