### ISSUE TITLE
`Cannot read properties of undefined (reading '_c')` while overriding the Details field

### ISSUE THREAD

**Issue by mrleblanc101** [outl1ne/nova-multiselect-field#179]
Hi,
I'm trying to overrider the Details Field but I get an error.

Here is what I did:
1) I copy-pasted the original `NovaMultiselectDetailFieldValue.vue` from the composer vendor. I didn't change anything for now.
2) I imported the component in my `app.js`. There was already a `require('./bootstrap');` which came with Nova, so I added it after.
3) I ran `npm install && npm run dev` which compiled successfully, after having installed `sass` and `sass-loader`, 
4) I registered the Javascript file in my  `NovaServiceProvider.php`.
5) I ran `php artisan nova:publish` and reloaded the page.
The component doesn't load and display this error in the console `TypeError: Cannot read properties of undefined (reading '_c')`.

```js
// app.js
require('./bootstrap');

import NovaMultiselectDetailFieldValue from './components/NovaMultiselectDetailFieldValue';

Nova.booting((Vue, router, store) => {
    Vue.component('nova-multiselect-detail-field-value', NovaMultiselectDetailFieldValue);
});

```

```php
// NovaServiceProvider.php
public function boot()
{
    parent::boot();
    Nova::script('app', public_path('js/app.js'));
}

**Comment by mrleblanc101** [comment]
![Capture d’écran, le 2022-10-18 à 17 09 31](https://user-images.githubusercontent.com/17392251/196545405-c8233418-d0fa-47a9-ace4-ac35689aa7a6.png)
![Capture d’écran, le 2022-10-18 à 17 09 40](https://user-images.githubusercontent.com/17392251/196545412-e554a49a-9963-4e36-a106-115cb895d2e2.png)

**Comment by mrleblanc101** [comment]
My Laravel starter-kit used an outdated version of Laravel Mix which compilted the component to Vue 2 syntax

**Comment by DuyenNguyen66** [comment]
please let me know where you placed NovaMultiselectDetailFieldValue.vue file. I placed it in project_name/resources/js/Components, but it not working

**Comment by mrleblanc101** [comment]
@DuyenNguyen66 it's written in the code block `./components/NovaMultiselectDetailFieldValue`. You can put it anywhere as long as your import is correct for Webpack I suppose.
