### ISSUE TITLE
Be able to set custom model key on async search  

### ISSUE THREAD

**Issue by aliwesome** [outl1ne/nova-multiselect-field#180]
I had to add a multiselect JSON field in which I needed custom `key => value`, also options were huge and would causes low performance on our dashboard.

So I decided to add it asynchronously but I couldn't set a custom key to load specific list as I want for previously saved ones.

Is there any way to extend current behavior to solve such issues?

**Comment by KasparRosin** [comment]
You can create a custom endpoint.

```php
# Usage
->api('/api/multiselect/artists', Artist::class),
```

**Comment by aliwesome** [comment]
@KasparRosin 

That doesn't fit my need, because I want to store another column of `Artist::class` like `username` or `slug` as the key.

I sent a PR yesterday, take a look at that. #181

**Comment by KasparRosin** [comment]
You should be able to do that with the endpoint?

The api endpoint needs to return `['id' => 'value']`, so you can return `[$artist->username => $artist->slug]` or whatever.

**Comment by aliwesome** [comment]
@KasparRosin 
There's issue with previous stored data as JSON, there's no `id` to load desired model, so the list will be empty but has data within.

**Comment by Tarpsvo** [comment]
Hey! I saw some room for improvement with your PR, so I did my own version of the same feature. Starting from release 4.2.0, you can use `->resourceKeyName('slug')` to achieve what you wanted. Please try it out and let me know if anything else needs to be done. :) Thanks!

**Comment by aliwesome** [comment]
@Tarpsvo 
That's great, thank you for your time.

I also added this functionality to nova-v3 branch on my new PR #188

**Comment by aliwesome** [comment]
Hey @Tarpsvo,
I've tested this package new version both on nova v3 and v4, there's a related issue that prevents full desired custom functionality.

The problem is that list of selected asyncResource data are not being stored via `resourceKeyName`, and it will pick `id` as default. 

As I saw different part of code, I've relieved it might be related to this section below:
https://github.com/outl1ne/nova-multiselect-field/blob/df141bdc189412c5481d69f851cc05a541ad2301/resources/js/components/FormField.vue#L362
