### ISSUE TITLE
Readonly visual bug in dark-mode

### ISSUE THREAD

**Issue by mrleblanc101** [outl1ne/nova-multiselect-field#182]
Weird grey square behind the arrow in dark mode when the field is readonly.
Also, the visual style of the field should match the default readonly field.
Currently, it use different colors.
<img width="1196" alt="Capture d’écran, le 2022-10-19 à 22 08 52" src="https://user-images.githubusercontent.com/17392251/196839548-e9ec323d-ce77-4334-8fe4-3cab2f7fa380.png">

**Comment by mrleblanc101** [comment]
Also somewhat present in light-mode
<img width="1169" alt="Capture d’écran, le 2022-10-19 à 22 10 27" src="https://user-images.githubusercontent.com/17392251/196839677-e017edd1-ef85-4d06-9ba4-eb33bf7a7046.png">

**Comment by mrleblanc101** [comment]
I cn open a PR for this

**Comment by mrleblanc101** [comment]
Fixed styles for dark-mode:
<img width="1166" alt="Capture d’écran, le 2022-10-19 à 23 13 52" src="https://user-images.githubusercontent.com/17392251/196847968-fa046974-a626-4fe9-a497-d55af24d1b8d.png">
Fixed styles for light-mode:
<img width="1154" alt="Capture d’écran, le 2022-10-19 à 23 15 03" src="https://user-images.githubusercontent.com/17392251/196848039-ef00bc4c-4478-48d4-a0b4-6774224a2460.png">

**Comment by mrleblanc101** [comment]
I found one more issue when using theme `system` on the Details View.

Dark mode:
<img width="1912" alt="Capture d’écran, le 2022-10-19 à 23 47 35" src="https://user-images.githubusercontent.com/17392251/196851868-22344a7b-ed7e-44ad-b16f-e1ca3c764ba0.png">
System mode:
<img width="1912" alt="Capture d’écran, le 2022-10-19 à 23 47 42" src="https://user-images.githubusercontent.com/17392251/196851897-dd6e1248-0eea-425b-9065-f609cde6e40d.png">

**Comment by Tarpsvo** [comment]
Heya! There was indeed an issue with the dark mode not applying when using the system theme. I fixed it in version 4.2.1. :)
