### ISSUE TITLE
Toggling readonly using `dependsOn` doesn't work

### ISSUE THREAD

**Issue by mrleblanc101** [outl1ne/nova-multiselect-field#183]
The dependsOn function is called and the condition work, but the UI doesnt' change.
The field does not become readonly.
```php
Multiselect::make('Persons', 'persons')
    ->dependsOn(['tv_show_member', 'company', 'tv_show'], function (Multiselect $field, NovaRequest $request, FormData $formData) {
        if($formData->tv_show_member || $formData->company || $formData->tv_show) {
            $field->readonly();
        }
    })
    ->belongsToMany(\App\Nova\Person::class, false)
    ->clearOnSelect()
    ->onlyOnForms(),
```

**Comment by mrleblanc101** [comment]
When changing readonly using dependsOn, we need to use `currentlyIsReadonly` I beleive from what I'm seeing in the Vue Devtools.
Didn't work for me, but `:disabled="currentField.readonly"` did work for me.
<img width="294" alt="Capture d’écran, le 2022-10-19 à 23 15 51" src="https://user-images.githubusercontent.com/17392251/196848202-55b5b543-63c1-46b2-8c92-3a394108b387.png">

**Comment by Tarpsvo** [comment]
You are absolutely correct. DependsOn uses 'currentField' as the latest state instead of 'field'.
