### ISSUE TITLE
BelongsToMany Issue - Incorrect integer value [object object]

### ISSUE THREAD

**Issue by acabreragnz** [outl1ne/nova-multiselect-field#193]
Hey Guys, how are you?
First of all, thank you for this amazing project!

Secondly, I'm having some issues with **BelongsToMany**, I have a **Course <-- N - N --> Keywords** 

- The list is correctly populated, but when I try to create/update the Course instance, then the **[Object object]** errors appear
![Screenshot from 2022-10-30 23-44-29](https://user-images.githubusercontent.com/6330366/198920941-ffc87af2-34ae-4189-ad44-86cb7fe51469.png)

- This is my **Course** nova file
![code](https://user-images.githubusercontent.com/6330366/198921144-b86f4fbb-38ae-42c0-8b08-39bf084cd6c3.png)

- This is my **Course** model file
![code2](https://user-images.githubusercontent.com/6330366/198921153-24e10ed8-c134-408f-9d1e-9e1d25bbea92.png)

What am I doing wrong? thank you in advance :)

**Comment by Tarpsvo** [comment]
Are you sure you don't have any other field with the attribute 'keywords' overwriting the FormData value? I tested it and can't reproduce this at all. Even when looking at the code, there's no way that a [object Object] with key `keywords` could appear.

If it's a multiselect field (which it is when looking at your code), it should appear as `keywords[0]: [object Object]` not just `keywords`.

**Comment by acabreragnz** [comment]
Thank you for your answer @Tarpsvo, I'll create a new fake relationship with a new Nova Resource in order to see if it is something from our code. I'll let you know tomorrow.

**Comment by acabreragnz** [comment]
I have the same result trying with other relationships, here is the request:

![image](https://user-images.githubusercontent.com/6330366/204717882-816e804e-9b13-4ad9-a487-6ea760e7daca.png)

**Comment by acabreragnz** [comment]
I tried a simple field with options and the same issue
![image](https://user-images.githubusercontent.com/6330366/204723507-34e002fc-bcb1-45ba-b3a1-07cbc501301d.png)
![image](https://user-images.githubusercontent.com/6330366/204723560-51395e2b-87e0-41ef-813c-8515984d30d5.png)

**Comment by DanOliveira98** [comment]
I have the same problem.

**Comment by daxo4** [comment]
Also being impacted by this issue since upgrading from `3.0.1` to `4.2.3` recently.  Was working without issue on the previous version but upgrading creates the exact issue reported here.  No code has changed on our side during the upgrade. 

Old version included the correct payload and now it's sending objects instead.  I'll try do a bit more digging.

**Comment by acabreragnz** [comment]
Thanks for the information @daxo4 I can confirm it because we use an older version of this field in another project, and it used to work without issues.

**Comment by brandonb927** [comment]
This is likely known by now but this issue is preventing our upgrade to Laravel v10
