### ISSUE TITLE
required doens't work

### ISSUE THREAD

**Issue by ronvanderheijden** [outl1ne/nova-multiselect-field#201]
Fields cannot be set to required nor nullable(false).

Example:
```
Multiselect::make('Types', 'types')
    ->nullable(false) // doesn't work
    ->required()      // doesn't work
    ->belongsToMany(\App\Nova\Type::class, false),
```

Result; you can create and update resources without selecting a type.

**Comment by KasparRosin** [comment]
You need to use ->rules('required').
The `required()` function is only for a callback to display the asterix. Does not apply the rule iteself.
