### ISSUE TITLE
[4.3.1] Breaks Create Form where default value not provided `Invalid default value...`

### ISSUE THREAD

**Issue by dmason30** [outl1ne/nova-multiselect-field#218]
Upgrading to 4.3.1 causes the below field to throw this error on a Create form (where there is no default because its creating a resource):

`Invalid default value. Value should be a single model or an array/collection of models.`

```php
Multiselect::make(trans('fields.branch'), 'branches')
   ->singleSelect()
   ->nullable()
   ->belongsToMany(BranchResource::class)
   ->onlyOnForms(),
```

The `$defaultValue` defined on line 169 here is `null` but it is being wrapped into an array `collect([null])` on line 172 and the each is looping it:

https://github.com/outl1ne/nova-multiselect-field/blob/cd2fda03f975f14910baf7a8eeb49d971193aaf0/src/Multiselect.php#L169-L175

**Comment by Tarpsvo** [comment]
Heya! Please try out 4.3.2. It should be fixed. ;)
