### ISSUE TITLE
"Attempt to read property "resourceClass" on null"

### ISSUE THREAD

**Issue by anandmainali5** [outl1ne/nova-multiselect-field#219]
I've this code in License.php resource file:
```
            Multiselect::make('Standards', 'standards')
            ->belongsToMany(\App\Nova\Central\Standard::class, false),
```

and this in in License.php model:

```
    public function standards()
    {
        return $this->belongsToMany(Standard::class);
    }
```
<img width="1503" alt="Screenshot 2023-06-01 at 12 12 20 PM" src="https://github.com/outl1ne/nova-multiselect-field/assets/96724138/0da20221-3cc1-4a99-ba21-ca875943fdfd">

Environment:
Laravel: ^10.4,
Nova: 4.22.1

**Comment by Tarpsvo** [comment]
Sounds like you're filtering some field out in your controller.

The line that crashes is:

```
$withTrashed = $this->shouldIncludeTrashed(
  $request, $associatedResource = $field->resourceClass
);
```

Meaning that $field was null. You should either array_filter() your fields. If you think you're not returning null, can you post your whole fields() function please. Thanks!

**Comment by anandmainali5** [comment]
@Tarpsvo here's my fields function in License.php resource file:
```
    public function fields(NovaRequest $request)
    {
        return [
            Text::make('Name')->rules('required'),
            Number::make('Validity in days', 'validity_in_days')->rules('required'),
            Date::make('Activated At', 'activated_at')->readonly()->hideWhenCreating()->hideWhenUpdating(),
            Date::make('Expires At', 'expires_at')->readonly()->hideWhenCreating()->hideWhenUpdating(),
            BelongsTo::make('Tenant')->DisplayUsing(function ($tenant) {
                return $tenant->msp_name . ' (' . $tenant->id . ')';
            })->rules('required'),
            Multiselect::make('Standards', 'standards')
            ->belongsToMany(\App\Nova\Central\Standard::class, false),
        ];
    }
```

**Comment by Tarpsvo** [comment]
Can't reproduce this. It shouldn't even make that API request if your async is set to false.

**Comment by anandmainali5** [comment]
@Tarpsvo issue has been solved. I was just refreshing the old url and thats why it was giving the issue.
The url was like: https://domain.com/nova/resources/licenses/2/attach/standards?viaRelationship=standards

**Comment by Tarpsvo** [comment]
Glad to hear that!
