### ISSUE TITLE
Multiselect belongsToMany (async false) duplicate queries (uncachable)

### ISSUE THREAD

**Issue by emcarson** [outl1ne/nova-multiselect-field#220]
Hi,

**When using Multiselect with the belongsToMany option and async disabled Multiselect generates 25 duplicate queries on the index page (one for each row):**

```
            Multiselect::make(__('Countries'), 'countries')
                ->belongsToMany(Country::class, false)
```
![Screenshot from 2023-06-14 15-56-52](https://github.com/outl1ne/nova-multiselect-field/assets/12752046/c11940b8-61f6-4bfb-b4ed-240c255870b9)

Am I doing something wrong? Is there a workaround or at least a way to Cache the query?
Thank you.

**Comment by Tarpsvo** [comment]
Hi! This seems like an issue on your side. Our code shouldn't do any SELECT * FROM somewhere when on the index view.

The line referenced just creates a NovaRequest and an empty model.

![image](https://github.com/outl1ne/nova-multiselect-field/assets/2018660/70b08578-b58a-47e6-a9a0-60ca962801ab)

Do you have a Country::all() in your model's constructor or in some observer/attribute?

However, when displaying a single value of the field - it will sadly do one request for each row. That's how it's intended in Nova. You could extend the base Model class and cache it in there somehow.
