### ISSUE TITLE
Belongs to feature doesn't work with lasts updates

### ISSUE THREAD

**Issue by proilyxa** [outl1ne/nova-multiselect-field#222]
When we try to create resource, we receive error.

<img width="764" alt="Снимок экрана 2023-06-28 в 18 18 29" src="https://github.com/outl1ne/nova-multiselect-field/assets/60401505/68498cfc-ff27-4442-bce7-f94c55143cf3">
<img width="1482" alt="Снимок экрана 2023-06-28 в 18 18 51" src="https://github.com/outl1ne/nova-multiselect-field/assets/60401505/26f94a28-642e-4be1-aef2-703fb4e1f912">

**Comment by proilyxa** [comment]
<img width="776" alt="Снимок экрана 2023-06-28 в 18 32 46" src="https://github.com/outl1ne/nova-multiselect-field/assets/60401505/95b352fa-81f7-4349-8095-aca626351c42">

this is fix for that

**Comment by Tarpsvo** [comment]
Heya! Thanks for the report. Should now be fixed in version 4.3.5. ;)
