### ISSUE TITLE
Getting this error after installing outline nova-menu-builder

### ISSUE THREAD

**Issue by Dmitrij-Kovrigin** [outl1ne/nova-multiselect-field#230]
![image](https://github.com/outl1ne/nova-multiselect-field/assets/85385077/0dc22219-7dba-4434-a6af-66f823f6b61f)

Error: Access level to Outl1ne\MultiselectField\Multiselect::resolveDefaultValue() must be public (as in class Laravel\Nova\Fields\Field)

Also in other nova resourse error appeared: The provided API key is invalid.

Resources without multiselect fields working properly.

some ideas how to fix this?

**Comment by Tarpsvo** [comment]
Should be fixed in version 4.4.0 (this was due to Nova's unexpected and unannounced method visibility change).
