### ISSUE TITLE
Create issue with belongsToMany if no option selected

### ISSUE THREAD

**Issue by Dmitrij-Kovrigin** [outl1ne/nova-multiselect-field#231]
There is an error, when trying to create or update resource. It appears when you dont select an option.

**Comment by Dmitrij-Kovrigin** [comment]
code example: 
                Multiselect::make('Country', 'countries')
                    ->hideFromIndex()
                    ->nullable()
                    ->belongsToMany(Country::class, false),

error: 
![image](https://github.com/outl1ne/nova-multiselect-field/assets/85385077/e83f3d16-9306-4d3e-bd83-e6e9f315167f)

**Comment by Tarpsvo** [comment]
Heya! Fixed in version 4.4.1. Sorry about that.
