### ISSUE TITLE
Adding a HasMany relation correctly

### ISSUE THREAD

**Issue by Norgul** [outl1ne/nova-multiselect-field#257]
I have a `parent_id` on my model table so I have used that to create parent/child relations:

```php
public function parent(): BelongsTo
{
    return $this->belongsTo(self::class, 'parent_id');
}

public function children(): HasMany
{
    return $this->hasMany(self::class, 'parent_id');
}
```

Relations work just fine (tried and tested in Tinker).

I have tried using it like this:
```php
Multiselect::make('Children', 'children')
    ->options(\App\Models\Tenant\Unit::all()->pluck('label', 'id'))
    ->taggable(false),
```

And I can pick & choose units from the list, however when I want to save it says 

> Column not found: 1054 Unknown column 'children' in 'field list'

**Comment by KasparRosin** [comment]
Multiselect currently does not support HasMany relationship, only belongsTo and belongsToMany.
There is sadly no way at the moment to add HasMany via Multiselect.

**Comment by Norgul** [comment]
Just wanted to add that in the mean time I have hacked it to work with `fillUsing()`, but reverted all of that as it makes no sense.

Reason it makes no sense is because it is essentially re-parenting children, changing their `parent_id` which might already be set. I would close this issue sooner would I not have forgotten I submitted it. 

I would support the decision to never implement this.
